### DISCUSSION TITLE
Catalog Item schema

### DISCUSSION THREAD

**Discussion by butchtm** [thinkingmachines/unicef-ai4d-research-bank#45] [Ideas]
This is to document the format of the catalog item.

Fields:
* id - generated? (initial pass: use filename (without extension) on folder -- guaranteed to be unique per folder if only using .yml  as extension and lower-case. )
* name (required)
* description (required)
* card type (required) -  values: 'model', 'dataset'
* links (one or more links, at least 1 required)
    * each link can/must have: 
        * url (required)
        * description (required)
        * type(required)  
            - proposed values: 'model-weights', 'dataset-csv', 'dataset-geojson', 'documentation', 'repository', 'code-python', 'code-rlang', 'code-notebook' (_note: can be expanded in the future_)
* organization - (required) (same as contributor?) - contains  the following:
   * name (required)
   * url (optional)
   * description (optional)
* date-added (required)
* date-modified (optional)
* tags (optional but highly recommended) - one or more tags where each tag is a word (no spaces, lower-case, no underscores, dash-allowed) 
* country/region (optional) - one or more countries/region, where each country/region is validated against a list
* year/period (optional)
* detail-image-url (generated) **NEW**
* used-by (optional) - list of items
     * each item has:
         * name (required)
         * url (optional) 
* evaluation metrics (optional) - one or more evaluation metric or a link 
     * each evaluation metric can have: 
           * metric type (required) 
           * value (required)
     * a link:
         *  description (required)
         * url  (required)
 
* data columns (optional)
   * each column can/must have: 
      * name (required)
      * type(optional) - string/number/date/etc
      * hxltag (optional) 
* sample data (optional) rows:
   * each row can/must have a list of values (each list must match list of columns)

Related items:
* [Catalog card page](https://github.com/thinkingmachines/unicef-ai4d-research-bank/issues/18)
* [Figma Prototype](https://www.figma.com/file/kh54B7nOM3PeE0OqnpqfU3/%5BSHARED%5D-Unicef-AI4D-Research-Bank?node-id=15-168)

**Comment by butchtm** [comment]
Sample yaml file:
```yaml
name: 'Poverty Mapping Model for Timor Leste'
description: 'This is a sklearn random forest regressor model  for predicting relative wealth for Timor Leste.  (add more details here later...)'
card-type: model
organization: 
  name: "Thinking Machines Data Sciences Inc"
  url: 'https://thinkingmachin.es'
date-added: '2023-03-02'
tags: 
  - poverty-mapping
  - timor-leste
country-region: timor-leste
# alternate format for multi country/region
country-region: 
  - timor-leste
  - philippines
  - malaysia
year-period: 2016
evaluation-metrics:
  - metric:
      metric-type: rsquared
      value: 0.59
 - link:
     description: 'Additional evaluation metrics discussion'
     url:  https://thinkingmachines.github.io/unicef-ai4d-poverty-mapping/notebooks/2023-01-17-initial-model-ph-mm-tl-kh/model_tl.html#evaluate-model-training-using-cross-validation
links:
  - url: https://github.com/thinkingmachines/unicef-ai4d-poverty-mapping/blob/main/notebooks/2023-02-21-single-country-rollouts/model_tl_rollout.pkl
    description: 'Timor Leste Poverty Mapping Model Weights (.pkl). See related notebooks for usage'
    type: model-weights
  - url: https://github.com/thinkingmachines/unicef-ai4d-poverty-mapping/blob/main/notebooks/2023-02-21-single-country-rollouts/rollout_output_tl.geojson
    description: 'Country wide rollout (inference) of the Poverty Mapping Model on Timor Leste using 2.4km grids (bingtile quadkey level 14)'
    type: 'dataset-geojson'
  - url: https://github.com/thinkingmachines/unicef-ai4d-poverty-mapping/blob/main/notebooks/2023-02-21-single-country-rollouts/2023-03-02-tl_final_model_rollout.ipynb
    description: 'Timor Leste Model Rollout Part 3 (Feature Engineering and Model Prediction on Rollout Grids)'
    type: 'code-notebook'
  - url: https://github.com/thinkingmachines/unicef-ai4d-poverty-mapping/blob/main/notebooks/2023-02-21-single-country-rollouts/2023_02-21-tl_final_model_training.ipynb
    description: 'Timor Leste Model Rollout Part 1 (Training Final Single-country Model)'
    type: 'code-notebook'
  - url: https://github.com/thinkingmachines/unicef-ai4d-poverty-mapping/blob/main/notebooks/2023-02-21-single-country-rollouts/2023-03-01-tl_generate_populated_grids.ipynb
    description: 'Timor Leste Model Rollout Part 2 (Generate Roll-out Grids)'
    type: 'code-notebook'
 
```
